language: scala
scala:
   - 2.12.7
jdk:
  - openjdk11

before_install:
  - sudo apt-get install -y ffmpeg

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "*[\[\]\(\)]*.properties" -type f -delete
